import type {
  DecisionCardData,
  DecisionServiceContract,
} from '@/types/family';

/**
 * CareSync Decision Inbox Service Contract
 * 
 * Manages Human-In-The-Loop (HITL) Decision Cards generated by backend care rules or future Strands AI Agents.
 * Clean abstraction seam ready for FastAPI backend endpoints (/api/v1/family/decisions).
 */
class CareSyncDecisionService implements DecisionServiceContract {
  public apiEndpoint = '/api/v1/family/decisions';

  async getPendingDecisions(caregiverId: string, parentId?: string): Promise<DecisionCardData[]> {
    console.info(`[DecisionService Contract] Fetching decisions for caregiver ${caregiverId}, parentId=${parentId}`);

    return [
      {
        id: 'dec-301',
        type: 'TRANSPORTATION_CONFIRMATION',
        priority: 'CRITICAL',
        status: 'PENDING',
        parentId: parentId || 'p-1',
        parentName: 'Susan Woodson (Mom)',
        title: 'Transportation Unconfirmed for Tomorrow\'s Appointment',
        summary: 'Mom has a Cardiology appointment tomorrow at 10:30 AM with Dr. Robert Chen. No family driver or volunteer has been assigned yet.',
        reason: 'CareSync Agent observed that Mom requested transport assistance 2 hours ago.',
        relatedEntityId: 'apt-201',
        actions: [
          { key: 'confirm_family_driver', label: 'I Will Drive Mom (09:45 AM)', variant: 'primary' },
          { key: 'request_volunteer_fallback', label: 'Assign Verified Volunteer Ride', variant: 'soft' },
          { key: 'reschedule_appointment', label: 'Reschedule Visit', variant: 'outline' },
        ],
        createdAt: '2 hours ago',
        expiresAt: 'In 3 hours',
      },
      {
        id: 'dec-302',
        type: 'VOLUNTEER_APPROVAL',
        priority: 'HIGH',
        status: 'PENDING',
        parentId: parentId || 'p-1',
        parentName: 'Susan Woodson (Mom)',
        title: 'Approve Community Volunteer Match',
        summary: 'Priya Sharma (Verified Community Volunteer, 1.4 km away) applied to assist Mom with pharmacy prescription pickup today at 4:00 PM.',
        reason: 'Priya has 4.9★ rating and completed 18 neighborhood care tasks.',
        relatedEntityId: 'req-301',
        actions: [
          { key: 'approve_volunteer', label: 'Approve Priya for Pickup', variant: 'primary' },
          { key: 'decline_volunteer', label: 'Decline & Keep Family Only', variant: 'outline' },
        ],
        createdAt: '30 mins ago',
        expiresAt: 'In 1 hour',
      },
    ];
  }

  async respondToDecision(
    decisionId: string,
    actionKey: string
  ): Promise<{ success: boolean; decision: DecisionCardData }> {
    console.info(`[DecisionService Contract] Responding to decision ${decisionId} with action ${actionKey}`);
    return {
      success: true,
      decision: {
        id: decisionId,
        type: 'TRANSPORTATION_CONFIRMATION',
        priority: 'LOW',
        status: 'ACCEPTED',
        parentId: 'p-1',
        parentName: 'Susan Woodson',
        title: 'Decision Resolved',
        summary: `Action ${actionKey} executed successfully.`,
        actions: [],
        createdAt: new Date().toISOString(),
      },
    };
  }
}

export const decisionService = new CareSyncDecisionService();
