import type {
  FamilyHomeReadModel,
  FamilyHomeServiceContract,
} from '@/types/family';
import { decisionService } from './decisionService';

/**
 * CareSync Family / Caregiver Home Read-Model Service
 * 
 * Aggregates dashboard data and decision inbox cards generated by the CareSync Agent (/api/v1/family/home).
 */
class CareSyncFamilyHomeService implements FamilyHomeServiceContract {
  public baseUrl = 'http://localhost:8000/api/v1';

  async getDashboard(caregiverId: string, parentId?: string): Promise<FamilyHomeReadModel> {
    console.info(`[FamilyHomeService] Fetching dashboard for caregiver ${caregiverId}, activeParentId=${parentId}`);

    const pid = parentId || 'p-1';
    try {
      const res = await fetch(`${this.baseUrl}/family/home?parent_id=${pid}`);
      if (res.ok) {
        const data = await res.json();
        const decisions = await decisionService.getPendingDecisions(caregiverId, pid);
        return {
          caregiverId: String(data.caregiver_id || caregiverId),
          caregiverName: String(data.caregiver_name || 'David Woodson'),
          activeParentId: pid,
          activeParentName: String(data.active_parent_name || 'Susan Woodson'),
          supportedParents: [
            { parentId: 'p-1', name: 'Susan Woodson', relationship: 'Mother', age: 74 },
            { parentId: 'p-2', name: 'George Miller', relationship: 'Father-in-law', age: 81 },
          ],
          attentionNeededCount: decisions.length,
          pendingDecisions: decisions,
          todayCareSummary: {
            checkInStatus: 'COMPLETED',
            checkInTime: '08:30 AM Today',
            medicationStatus: 'PARTIAL',
            takenMedsCount: 1,
            totalMedsCount: 3,
            appointmentStatus: 'TRANSPORT_NEEDED',
            upcomingAppointmentTitle: 'Cardiology Routine Check-Up',
            upcomingAppointmentTime: 'Tomorrow at 10:30 AM',
          },
          recentActivity: [
            { id: 'act-1', timestamp: '08:30 AM', text: 'Daily safety check-in completed: "I am doing well"', category: 'CHECK_IN', actorName: 'Susan Woodson' },
            { id: 'act-2', timestamp: '08:35 AM', text: 'Lisinopril (10 mg) recorded as taken', category: 'MEDICATION', actorName: 'Susan Woodson' },
            { id: 'act-3', timestamp: '09:15 AM', text: 'Transportation help requested for Cardiology visit', category: 'TRANSPORTATION', actorName: 'Susan Woodson' },
            { id: 'act-4', timestamp: '09:20 AM', text: 'CareSync Agent observed missing transport assignment and created Decision Card', category: 'AGENT', actorName: 'CareSync Agent' },
          ],
        };
      }
    } catch {
      console.warn('[FamilyHomeService] Backend offline during dashboard fetch.');
    }

    const decisions = await decisionService.getPendingDecisions(caregiverId, pid);

    return {
      caregiverId,
      caregiverName: 'David Woodson',
      activeParentId: pid,
      activeParentName: pid === 'p-2' ? 'George Miller' : 'Susan Woodson',
      supportedParents: [
        { parentId: 'p-1', name: 'Susan Woodson', relationship: 'Mother', age: 74 },
        { parentId: 'p-2', name: 'George Miller', relationship: 'Father-in-law', age: 81 },
      ],
      attentionNeededCount: decisions.length,
      pendingDecisions: decisions,
      todayCareSummary: {
        checkInStatus: 'COMPLETED',
        checkInTime: '08:30 AM Today',
        medicationStatus: 'PARTIAL',
        takenMedsCount: 1,
        totalMedsCount: 3,
        appointmentStatus: 'TRANSPORT_NEEDED',
        upcomingAppointmentTitle: 'Cardiology Routine Check-Up',
        upcomingAppointmentTime: 'Tomorrow at 10:30 AM',
      },
      recentActivity: [
        { id: 'act-1', timestamp: '08:30 AM', text: 'Daily safety check-in completed: "I am doing well"', category: 'CHECK_IN', actorName: 'Susan Woodson' },
        { id: 'act-2', timestamp: '08:35 AM', text: 'Lisinopril (10 mg) recorded as taken', category: 'MEDICATION', actorName: 'Susan Woodson' },
        { id: 'act-3', timestamp: '09:15 AM', text: 'Transportation help requested for Cardiology visit', category: 'TRANSPORTATION', actorName: 'Susan Woodson' },
        { id: 'act-4', timestamp: '09:20 AM', text: 'CareSync Agent observed missing transport assignment and created Decision Card', category: 'AGENT', actorName: 'CareSync Agent' },
      ],
    };
  }
}

export const familyHomeService = new CareSyncFamilyHomeService();
