"""0002_add_processed_events

Revision ID: 13332ccecb56
Revises: 7afa1fae04fa
Create Date: 2026-08-19 14:37:49.582138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13332ccecb56'
down_revision: Union[str, None] = '7afa1fae04fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('consumer_name', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'consumer_name', name='uq_event_consumer')
    )
    op.create_index(op.f('ix_processed_events_consumer_name'), 'processed_events', ['consumer_name'], unique=False)
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_consumer_name'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
