"""0003_add_notification_records

Revision ID: 7df96b1668f5
Revises: 13332ccecb56
Create Date: 2026-08-19 14:43:24.347978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df96b1668f5'
down_revision: Union[str, None] = '13332ccecb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_records',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'recipient_id', 'notification_type', name='uq_notification_dedup')
    )
    op.create_index(op.f('ix_notification_records_event_id'), 'notification_records', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_records_notification_type'), 'notification_records', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_records_recipient_id'), 'notification_records', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notification_records_status'), 'notification_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_records_status'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_recipient_id'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_notification_type'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_event_id'), table_name='notification_records')
    op.drop_table('notification_records')
    # ### end Alembic commands ###
